containers:
  - name: my-app
    image: my-app:latest  # Update this line with your image name and tag
    ports:
      - containerPort: 5000
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 3
      periodSeconds: 3
